### ISSUE TITLE
I have a error in port 80

### ISSUE THREAD

**Issue by Dazmed707** [D00Movenok/BounceBack#11]
<img width="764" alt="image" src="https://github.com/D00Movenok/BounceBack/assets/35184132/83616d30-d8c6-4dfe-8b56-7906a8dcef6c">

I have an error on port 80, I am using gophish already executed in tmux, any way to resolve if gophish is using it, or change the port to another?

I'm going to try changing the local port in the config
<img width="268" alt="image" src="https://github.com/D00Movenok/BounceBack/assets/35184132/375a77bd-d15f-4be1-8c99-5cec90c5c6b9">

SAME ERROR
<img width="551" alt="image" src="https://github.com/D00Movenok/BounceBack/assets/35184132/49bd58b2-68c7-4b49-94c5-3a2d79777f01">

**Comment by D00Movenok** [comment]
Just check what is using port 80 using `netstat -tulpn` and then rebind it.

After changing the local port in the config, it looks like you are not saving it because of the logs ;)

**Comment by Dazmed707** [comment]
I have this results with netstat -tulpn

<img width="582" alt="image" src="https://github.com/D00Movenok/BounceBack/assets/35184132/2c9ce16b-1c9b-46f0-86e8-96760006982e">

**Comment by D00Movenok** [comment]
This project is not a support for your gophish and evilginx infta setup. If you need support for this tools - ask their own authors.

However, if you don't know basics about deploying this tools, it's better to read the docs before asking. It's also better to understand how the network works and then try to configure network services. If you think that I must resolve your basic network issues without trying to understand it by yourself - you'r a script kiddie.

For better understanding of networks you may read this book:
https://www.amazon.com/Computer-Networks-Global-Andrew-Tanenbaum/dp/1292374063
https://www.amazon.com/Computer-Networks-Principles-Technologies-Protocols/dp/0470869828
